import { useState } from 'react';
import jsPDF from 'jspdf';
import { formatFileSize } from '../utils/validators';

// Brand colors (RGB) used throughout the PDF report.
const BRAND = [38, 78, 156];
const SLATE_DARK = [30, 41, 59];
const SLATE_MID = [100, 116, 139];
const SLATE_LIGHT = [226, 232, 240];

const LEVEL_COLORS = {
  Safe: [22, 163, 74],
  'Moderate Risk': [217, 119, 6],
  'High Risk': [220, 38, 38]
};

const LEVEL_BG = {
  Safe: [240, 253, 244],
  'Moderate Risk': [255, 251, 235],
  'High Risk': [254, 242, 242]
};

const MARGIN = 44;
const FOOTER_HEIGHT = 34;

/**
 * Draws a simple vector shield logo (no external image needed) at the
 * given top-left position with the given size.
 */
function drawShieldLogo(doc, x, y, size) {
  const w = size;
  const h = size * 1.05;
  doc.setFillColor(...BRAND);
  doc.lines(
    [
      [w * 0.5, 0],
      [w * 0.5, h * 0.15],
      [0, h * 0.35],
      [0, h * 0.15],
      [-w * 0.5, h * 0.35],
      [0, h * 0.35]
    ],
    x, y,
    [1, 1],
    'F'
  );
  // Checkmark
  doc.setDrawColor(255, 255, 255);
  doc.setLineWidth(1.6);
  doc.lines([[w * 0.18, h * 0.18], [w * 0.14, -h * 0.24]], x + w * 0.28, y + h * 0.5, [1, 1], 'S');
}

/**
 * Renders a wrapped bullet list starting at (x, y) and returns the new y.
 */
function drawBulletList(doc, items, x, y, maxWidth, lineHeight = 13) {
  doc.setFontSize(10);
  doc.setTextColor(...SLATE_DARK);
  items.forEach((item) => {
    const lines = doc.splitTextToSize(item, maxWidth - 12);
    doc.setFillColor(...BRAND);
    doc.circle(x + 2, y - 3, 1.3, 'F');
    doc.text(lines, x + 10, y);
    y += lines.length * lineHeight;
  });
  return y;
}

function drawSectionTitle(doc, text, x, y) {
  doc.setFontSize(11.5);
  doc.setFont(undefined, 'bold');
  doc.setTextColor(...BRAND);
  doc.text(text, x, y);
  doc.setFont(undefined, 'normal');
  return y + 16;
}

/**
 * Draws one of the small stat "cards" (Risk Score, Confidence, etc.)
 */
function drawStatCard(doc, x, y, w, h, label, value) {
  doc.setFillColor(248, 250, 252);
  doc.setDrawColor(...SLATE_LIGHT);
  doc.roundedRect(x, y, w, h, 4, 4, 'FD');
  doc.setFontSize(8.5);
  doc.setTextColor(...SLATE_MID);
  doc.text(label, x + 10, y + 16);
  doc.setFontSize(14);
  doc.setFont(undefined, 'bold');
  doc.setTextColor(...SLATE_DARK);
  doc.text(String(value), x + 10, y + 32);
  doc.setFont(undefined, 'normal');
}

export default function PdfDownloadButton({ result }) {
  const [generating, setGenerating] = useState(false);

  function addFooters(doc) {
    const pageCount = doc.internal.getNumberOfPages();
    const pageWidth = doc.internal.pageSize.getWidth();
    const pageHeight = doc.internal.pageSize.getHeight();
    for (let i = 1; i <= pageCount; i++) {
      doc.setPage(i);
      doc.setDrawColor(...SLATE_LIGHT);
      doc.line(MARGIN, pageHeight - FOOTER_HEIGHT, pageWidth - MARGIN, pageHeight - FOOTER_HEIGHT);
      doc.setFontSize(8.5);
      doc.setTextColor(...SLATE_MID);
      doc.text('Generated by ThreatLens', pageWidth / 2, pageHeight - FOOTER_HEIGHT + 14, { align: 'center' });
      doc.text('Educational Cybersecurity Assessment Tool', pageWidth / 2, pageHeight - FOOTER_HEIGHT + 26, {
        align: 'center'
      });
    }
  }

  async function handleDownload() {
    if (!result) return;
    setGenerating(true);

    try {
      const doc = new jsPDF({ unit: 'pt', format: 'a4' });
      const pageWidth = doc.internal.pageSize.getWidth();
      const pageHeight = doc.internal.pageSize.getHeight();
      const contentWidth = pageWidth - MARGIN * 2;
      const maxY = pageHeight - FOOTER_HEIGHT - 16;

      function ensureSpace(doc2, currentY, needed) {
        if (currentY + needed > maxY) {
          doc2.addPage();
          return MARGIN;
        }
        return currentY;
      }

      let y = MARGIN;

      // ---------- HEADER ----------
      drawShieldLogo(doc, MARGIN, y, 22);
      doc.setFontSize(19);
      doc.setFont(undefined, 'bold');
      doc.setTextColor(...BRAND);
      doc.text('THREATLENS', MARGIN + 34, y + 16);
      doc.setFont(undefined, 'normal');
      doc.setFontSize(9.5);
      doc.setTextColor(...SLATE_MID);
      doc.text('Cyber Threat Intelligence Report', MARGIN + 34, y + 30);

      const now = new Date();
      doc.setFontSize(8.5);
      doc.setTextColor(...SLATE_MID);
      doc.text(`Scan ID: ${result.scanId || 'N/A'}`, pageWidth - MARGIN, y + 4, { align: 'right' });
      doc.text(`Date: ${now.toLocaleDateString()}`, pageWidth - MARGIN, y + 16, { align: 'right' });
      doc.text(`Time: ${now.toLocaleTimeString()}`, pageWidth - MARGIN, y + 28, { align: 'right' });

      y += 44;
      doc.setDrawColor(...SLATE_LIGHT);
      doc.line(MARGIN, y, pageWidth - MARGIN, y);
      y += 22;

      // ---------- TARGET INFORMATION ----------
      y = drawSectionTitle(doc, 'Target Information', MARGIN, y);
      doc.setFontSize(10);
      doc.setTextColor(...SLATE_DARK);

      if (result.type === 'file') {
        const rows = [
          ['File Name', result.fileName || 'N/A'],
          ['File Type', (result.fileType || 'Unknown').toUpperCase()],
          ['File Size', formatFileSize(result.fileSize || 0)],
          ['SHA256', result.sha256 || 'Unavailable']
        ];
        rows.forEach(([label, value]) => {
          doc.setTextColor(...SLATE_MID);
          doc.text(`${label}:`, MARGIN, y);
          doc.setTextColor(...SLATE_DARK);
          const lines = doc.splitTextToSize(value, contentWidth - 90);
          doc.text(lines, MARGIN + 90, y);
          y += lines.length * 13;
        });
      } else {
        doc.setTextColor(...SLATE_MID);
        doc.text(`${result.type.toUpperCase()}:`, MARGIN, y);
        doc.setTextColor(...SLATE_DARK);
        const lines = doc.splitTextToSize(result.target || 'N/A', contentWidth - 60);
        doc.text(lines, MARGIN + 60, y);
        y += lines.length * 13;
      }
      y += 14;

      // ---------- RISK ASSESSMENT STAT CARDS ----------
      y = ensureSpace(doc, y, 60);
      const cardGap = 10;
      const cardWidth = (contentWidth - cardGap * 3) / 4;
      const cardHeight = 44;
      drawStatCard(doc, MARGIN, y, cardWidth, cardHeight, 'RISK SCORE', `${result.riskScore}%`);
      drawStatCard(doc, MARGIN + (cardWidth + cardGap), y, cardWidth, cardHeight, 'RISK LEVEL', result.riskLevel);
      drawStatCard(doc, MARGIN + (cardWidth + cardGap) * 2, y, cardWidth, cardHeight, 'CONFIDENCE', `${result.confidence}%`);
      drawStatCard(
        doc,
        MARGIN + (cardWidth + cardGap) * 3,
        y,
        cardWidth,
        cardHeight,
        'DETECTIONS',
        result.detectionRatio || 'N/A'
      );
      y += cardHeight + 24;

      // ---------- THREAT INTELLIGENCE SUMMARY ----------
      if (result.summary && result.summary.length > 0) {
        y = ensureSpace(doc, y, 40);
        y = drawSectionTitle(doc, 'Threat Intelligence Summary', MARGIN, y);
        y = drawBulletList(doc, result.summary, MARGIN, y, contentWidth);
        y += 12;
      }

      // ---------- THREAT FINDINGS ----------
      if (result.findings && result.findings.length > 0) {
        y = ensureSpace(doc, y, 40);
        y = drawSectionTitle(doc, 'Threat Findings', MARGIN, y);
        y = drawBulletList(doc, result.findings, MARGIN, y, contentWidth);
        y += 12;
      }

      // ---------- RECOMMENDATIONS ----------
      if (result.recommendations && result.recommendations.length > 0) {
        y = ensureSpace(doc, y, 40);
        y = drawSectionTitle(doc, 'Security Recommendations', MARGIN, y);
        y = drawBulletList(doc, result.recommendations, MARGIN, y, contentWidth);
        y += 14;
      }

      // ---------- FINAL VERDICT BOX ----------
      const verdictBoxHeight = 50;
      y = ensureSpace(doc, y, verdictBoxHeight + 10);
      const levelColor = LEVEL_COLORS[result.riskLevel] || LEVEL_COLORS.Safe;
      const levelBg = LEVEL_BG[result.riskLevel] || LEVEL_BG.Safe;
      doc.setFillColor(...levelBg);
      doc.setDrawColor(...levelColor);
      doc.setLineWidth(1.2);
      doc.roundedRect(MARGIN, y, contentWidth, verdictBoxHeight, 6, 6, 'FD');

      doc.setFontSize(8.5);
      doc.setTextColor(...SLATE_MID);
      doc.text('FINAL VERDICT', MARGIN + 16, y + 18);

      doc.setFontSize(15);
      doc.setFont(undefined, 'bold');
      doc.setTextColor(...levelColor);
      doc.text(result.finalVerdict || 'N/A', MARGIN + 16, y + 38);
      doc.setFont(undefined, 'normal');

      doc.setFontSize(9.5);
      doc.setTextColor(...levelColor);
      doc.text(result.riskLevel.toUpperCase(), pageWidth - MARGIN - 16, y + 28, { align: 'right' });

      addFooters(doc);

      doc.save(`ThreatLens-Report-${result.scanId || Date.now()}.pdf`);
    } catch (error) {
      console.error('PDF generation failed:', error);
      alert('Something went wrong while generating the PDF. Please try again.');
    } finally {
      setGenerating(false);
    }
  }

  return (
    <button onClick={handleDownload} disabled={generating} className="btn-secondary w-full sm:w-auto">
      {generating ? 'Generating PDF...' : 'Download Security Report'}
    </button>
  );
}
